const climaticType = {
    'tempestade': 'wi-thunderstorm',
    'chuvisco': 'wi-sprinkle',
    'chuva': 'wi-rain',
    'neve': 'wi-snow',
    'névoa': 'wi-fog',
    'fumaça': 'wi-smoke',
    'neblina seca': 'wi-day-haze',
    'poeira': 'wi-dust',
    'névoa densa': 'wi-day-fog',
    'areia': 'wi-sandstorm',
    'cinzas': 'wi-volcano',
    'rajada de vento': 'wi-strong-wind',
    'tornado': 'wi-tornado',
    'céu limpo': 'wi-day-sunny',
    'poucas nuvens': 'wi-day-cloudy',
    'algumas nuvens': 'wi-cloud',
    'nublado': 'wi-cloudy',
    'nuvens dispersas': 'wi-day-cloudy-high',
    'chuva com trovoadas': 'wi-thunderstorm',
    'tempestade elétrica': 'wi-thunderstorm',
    'chuva fraca': 'wi-sprinkle',
    'chuva forte': 'wi-rain',
    'chuva congelante': 'wi-rain-mix',
    'neve leve': 'wi-snow',
    'neve pesada': 'wi-snow-wind',
    'chuva com neve': 'wi-rain-mix',
    'chuva e neve': 'wi-rain-mix',
    'nevoeiro leve': 'wi-fog',
    'nevoeiro': 'wi-fog',
    'nevoeiro pesado': 'wi-fog',
    'geada': 'wi-fog',
    'poeira em suspensão': 'wi-dust',
    'nebulosidade': 'wi-sandstorm',
    'vendaval': 'wi-windy',
    'calor': 'wi-hot',
    'frio': 'wi-snowflake-cold',
    'ventania': 'wi-windy',
    'tempestade de areia': 'wi-sandstorm',
    'furacão': 'wi-hurricane',
    'tempestade tropical': 'wi-storm-warning',
    'chuva com granizo': 'wi-hail'
  };
  